### ISSUE TITLE
tap event fire 2 times

### ISSUE THREAD

**Issue by vallemar** [nativescript-vue/nativescript-vue#1010]
Using the stackblitz example from the repository, you can check that if you tap on the text the event is fired twice and the method `logMessage` is executed 2 times. (It also happens at my local)

**Comment by rigor789** [comment]
This happens here:

https://github.com/nativescript-vue/nativescript-vue/blob/26ac884a9a8dc60a18e80cd005a1eca4eb8248ba/src/dom/index.ts#L166-L167

Still looking into the proper fix, but the issue is that `@loaded` and `@Loaded` both become `onLoaded` in the compiled template, so inferring case-senstive events is tricky.

One solution I can think of is to treat `onX` by stripping `on` (like we already do) and then converting x to lower case and keeping the rest as-is.

We could override the core behavior in a custom compiler too, but not sure if it's worth the maintenance effort on that side.

There's also a fix that's available only when `isCustomElement` returns true (from compiler options), which uses the `on:loaded`/`on:Loaded` syntax (so preserves casing), but that means we need to know the list of custom elements at compile time - which just adds overhead in the build setup.

**Comment by vallemar** [comment]
perfect, if it has no performance implications and it just works, that's fine! 🚀
