### ISSUE TITLE
vite support

### ISSUE THREAD

**Issue by Fuzzyma** [nativescript-vue/nativescript-vue#1058]
Do you plan on supporting vite instead of webpack?

**Comment by rigor789** [comment]
Not at the moment, webpack is currently an essential part of the build pipeline as it needs to resolve platform specific paths/extensions, transform `@NativeClass` decorators and a few more things.

Theoretically, we could build the bundle with vite - however doing HMR with vite would be quite difficult because it's based around browser specific features that wouldn't work out of the box in NativeScript. Those would likely need to be shimmed/implemented by both ios and android runtimes with v8/c++ apis.
