### ISSUE TITLE
How Vue components work??

### ISSUE THREAD

**Issue by nusendra** [nativescript-vue/nativescript-vue#115]
I'm new with nativescript and i want to build mobile app with vuejs.

How can i import other component to the main page? How to use this with .vue single file??
Thanks

**Comment by aaronksaunders** [comment]
There is a webpack template that is supposed to support single file components, but it is not fully functional. I have been trying to figure this out for weeks with very little success

**Comment by filrak** [comment]
just use `@import` statement on the top of the `.vue` file. Then register the imported object in `components` object of your Vue component  Like this
![image](https://user-images.githubusercontent.com/15185752/36342650-bfdd6cd8-1401-11e8-8936-1715cb97c051.png)

**Comment by nkostadinov** [comment]
I'm also waiting for components to work before doing anything

**Comment by nusendra** [comment]
i think i don't want to use this NS Vue right now, until single vue file and separated router file works like pure vuejs. Or maybe there is solutions for this? But i can't find out in the docs.

**Comment by jlooper** [comment]
If it will help, check my elocute mobile app which uses the patterns you need, I think. Github.com/jlooper/elocute in the mobile folder

**Comment by rigor789** [comment]
Our next goal is to improve the available templates. We are also planning to create a plugin for the new vue cli (3.x) which should make it easier to keep updated. As stated before, for .vue files to work you need to use a template that precompiles them to javascript. A good starting point would be the webpack template by @tralves which is used in @jlooper's elocute app. Routing is working the same as on the web, and you can move it to a separate / dedicated file if you want to. 
There is a slight difference though, which is not yet documented. The default behavior of the router is component-based routing, which means that in the page where you use `<router-view/>` the current routes component will get swapped in-and-out, while if you enable `pageRouting` in the routers config (https://github.com/nativescript-vue/nativescript-vue/blob/master/samples/app/app-with-router-pages.js#L47) you don't need (as it will be ignored) a render function or a template for the root Vue instance, because the router will open a new page for every route. I hope to get this documented within a week!

**Comment by nusendra** [comment]
ah thanks @jlooper. i will take a look in ur repository. thanks 

@rigor789 thanks for the explanation. i will try jlooper's way

thanks all

**Comment by nusendra** [comment]
hello, now i can get this working. 
i create new project with this
https://github.com/tralves/nativescript-vue-webpack-template

then i modify the package.json 
"nativescript-vue": "^0.1.1",
into this
"nativescript-vue": "github:tralves/nativescript-vue",

**Comment by rigor789** [comment]
`tralves/nativescript-vue` is a fork that was used to create a pull request into the main project, and hasn`t been touched since october. Lots of work went into the project since then so please use the official package.

**Comment by nusendra** [comment]
ah i get it now. thanks @rigor789 

i create new project with 
tns create my-app --template nativescript-vue-template

then i change the default nativescript-vue
"nativescript-vue": "^0.1.1",
to this
"nativescript-vue": "^1.0",

but when i try to implement import file, i got the error.
import Vue from 'nativescript-vue'
but this working perfectly
const Vue = require('nativescript-vue/dist/index')

How can i achieve this? thanks

**Comment by xlcrr** [comment]
`const Vue = require('nativescript-vue/dist/index');`
works for me
PS <3 for 1.0

**Comment by nusendra** [comment]
const Vue = require('nativescript-vue/dist/index');
this work for me too

but how to implement like this
import Vue from 'nativescript-vue/dist/index'

@xlcrr

**Comment by rigor789** [comment]
That syntax is only supported through webpack, since it is not natively supported in v8

**Comment by nusendra** [comment]
thanks @rigor789
