### ISSUE TITLE
RFC: VueRouter behavior

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue#119]
VueRouter mostly works with NativeScript-Vue out of the box, except a few little issues that some people are facing.

Now that we have pushed out the 1.0 release, we can discuss how to make the VueRouter integration better, and more appropriate for mobile applications.

Right now you can use `router.push()` and `router.replace()` to change the active route. It has been a little while since I made this all work, so I'll have to go back and figure out what's the difference between the two (will update this issue when I do).

From a mobile application development perspective, I would like to get some input on what You expect from a router to do.

I'm mainly interested if we should make `router.push()` add new pages (when talking about `pageRouting`) to the navigation stack, and the back buttons would pop the stack, and go back.

And on the other hand make `router.replace()` pop the stack, and push a new page into it, effectively replacing the current page. This would mean that the back button would go back to the previous page/starting page and not the page that was in the stack when `router.replace()` was called.

Is this the behavior that would make the most sense?

Are there any other features that you would expect from the router?

Currently (undocumented at this point) you can set the transition using the `router.setPageTransition(transition, duration, curve)` method.

**Comment by chrishaff** [comment]
I generally agree with the approach, though I can't really think of a reason for replace() or why it's necessary if all there is to it is pop() followed by push().

**Comment by MichelChouinard** [comment]
I do agree with the idea.

My point of view is that the `router.replace()` method is more a way to prevent the use of the browser back/forward buttons for a **web app**.  One can use only `router.replace()` instead of `router.push()` and manually control everything.  

There is no hard back button in iOS but there is one in Android.  So router.replace() is still useful to keep page level hierarchy.  Say, main page tabs are level 1 (no back between them), pages opened by them are level 2 (back button, hard or soft, goes back 1 level down), etc...

So both have their use cases and `router.replace()` should pop and push to the stack.

**Comment by mrmonat** [comment]
It would be great, if `router.replace()` wouldn't add the page to the navigation stack, because if you try to use _**RadSideDrawer**_ with **_vue-router_**, there is no way to tell the links / buttons from the drawer to open the specified route without pushing it to the nav stack _(or at least i didn't find a solution)_. So you end up with a back button (on iOS), when selecting an entry from the side drawer.

So ideally the buttons inside the drawer should switch pages by calling `router.replace()`.

"Deeper" pages inside those "main pages" should call `router.push()` to add the "deeper" pages to the nav stack.

**Comment by mdaliyan** [comment]
I'm thinking about a way to keep the data and scroll position in a page when we redirect  the user to a new route, and keep track of them when user goes through a chain of routes. when user goes back to previous page he/she expects not be at the position he/she left it, right? 

I can't think of a solution yet.

**Comment by rigor789** [comment]
@mdaliyan with `router.push()` new pages are added to the stack, and older ones are not destroyed. That means that all the data and scroll position should be intact once the user navigates back. With `router.replace()` you are **replacing** the current route, and the back button will go back to the previous route (still keeping the scroll / data on the previous page if it's not the first one in the stack, in which case it should just exit the application).

Speaking of exiting the application, do we need to provide a configuration for the exit behavior? For example in some apps people like to exit the app only if the back button is pressed twice in rapid succession. Is that something that we should allow by default?

**Comment by mdaliyan** [comment]
@rigor789 thank you. I just repeat so i get asure I get it right... you said

> with `router.push()` ...  all the data and scroll position should be intact once the user navigates back. 

and

> With `router.replace()` ... still keeping the scroll / data on the previous page.

so no matter what method we chose. the data and scroll position will be kept. That is so good.

and about the exiting the app with double tap on back botton... I like that and if you set it as default I won't change it. But it would be good if you provide an alternative way like confirming or any other way a some developers like.

**Comment by rigor789** [comment]
I'm thinking more like a callback function which gets called before exiting, where it could be prevented. So double tap to exit would be implemented by the user and not by nativescript-vue itself.

**Comment by mdaliyan** [comment]
but what would be the default behaviour for back button on first page? simply exit by one tap?

**Comment by tlgreg** [comment]
No default behavior would be the best, just handle in the callback as you wish.

**Comment by rigor789** [comment]
Moving discussion to https://github.com/nativescript-vue/nativescript-vue/issues/214
