### ISSUE TITLE
Consecutive `v-if` stop reactive properties

### ISSUE THREAD

**Issue by Tronix117** [nativescript-vue/nativescript-vue#127]
Whenever in the same hierarchy, there are multiple `v-if`, and a `v-if` become `true`, all reactive properties stop working altogether. This means all Vue reactive properties does not work anymore in the entire app, even if the page is destroyed. The only way is to reload the app.

As a workaround:`v-if` along `v-else-if` or `v-else` are not affected, `v-show` is also not affected.

The bug has been reproduced by @rigor789 .

---

This causes the issue:
```pug
Page
  StackLayout
    Label(
      v-if="foo"
      text="Enable"
      @tap="foo = false"
    )

    Label(
      v-if="!foo"
      text="Disable"
      @tap="foo = true"
    )
```

However this is working:
```pug
Page
  StackLayout
    Label(
      v-if="foo"
      text="Enable"
      @tap="foo = false"
    )

    Label(
      v-else
      text="Disable"
      @tap="foo = true"
    )
```

And this is also working:
```pug
Page
  StackLayout
    Label(
      v-show="foo"
      text="Enable"
      @tap="foo = false"
    )

    Label(
      v-show="!foo"
      text="Disable"
      @tap="foo = true"
    )
```

**Comment by rigor789** [comment]
**Update**: Looks like the difference between the working/non-working example (in terms of the render function) is that the working `v-if/v-else` code generates a render function like so:
```js
[
 (foo) ? _c(Enable) : _c(Disable)
]
```
(shortened here), while the consecutive `v-if` version generates
```js
[
  (foo) ? _c(Enable) : _e(),
  (!foo) ? _c(Disable) : _e(),
]
```

`_e()` creates an empty VNode, which is represented as a CommentNode (or TextNode - can't remember). 

The issue lies in the logic of `insertBefore` which tries to insert before the empty VNode.

I need to re-visit the whole renderer - which will take some time, but at least the cause is now known!

**Comment by msaelices** [comment]
@rigor789 I'm not sure if the fix is completely working. Sometimes if you remove and add a vnode from the tree the order change!
