### ISSUE TITLE
Using pageRouting with custom navigation (eg nativescript-bottombar)

### ISSUE THREAD

**Issue by academici** [nativescript-vue/nativescript-vue#140]
If use pageRouting option, App.vue template is ignored

**Comment by rigor789** [comment]
Hi, can you be a little more specific about the issue you are having? 

Another thing to note, pageRouting is experimental, and not currently recommended.

**Comment by academici** [comment]
You can mark this as a new feature. This is a popular layout for modern apps

**Comment by rigor789** [comment]
I still don't know what you are asking about, can you please go into more detail?

**Comment by academici** [comment]
I develop app with tab based structure. 

`<page class="page" :class="pageClass" @loaded="appLoaded">
      <ActionBar :title="title" class="action-bar text-center" :visibility="hasActionbar ? 'visible' : 'collapsed'" ref="actionbar">
        <android>
          <NavigationButton :visibility="back ? 'visible' : 'collapsed'" icon="res://ic_menu_black_24dp" android.systemIcon="ic_menu_back" @tap="$router.push(back)" />
        </android>
      </ActionBar>
      <GridLayout rows="*, auto">
        <router-view></router-view>
        <BottomBar :visibility="hasBottombar ? 'visible' : 'collapsed'" row="1" :items="tabsBottombar" 
          @loaded="tabLoaded" @tabSelected="tabSelected"
          :hide="bbConfig.hidden" :titleState="bbConfig.titleState" :inactiveColor="bbConfig.inactiveColor" :accentColor="bbConfig.accentColor" 
          :colored="bbConfig.colored" uncoloredBackgroundColor="#E1F5FE"> 
        </BottomBar>
      </GridLayout>
		</page>`

When clicking on the android button on the back button the application closes.
There are problems when using vuex. state is not always updated in App.vue (In console correct data, in layout not)
There is no animation between the transitions between the pages.
I think navigating through the pages would solve this problem

**Comment by rigor789** [comment]
Okay, I think I understand what you are looking for, basically you want a tab based application, which uses pages for each tab (correct me if I'm wrong), and you want the back button to go back instead of quitting.

There are a few problems I can see with the code you pasted, it uses `<router-view>` which is for component based routing, and not page routing. The difference is that component based routes will insert the resolved route component where the `<router-view>` is, and when the route changes it will replace that part of the page. This uses only 1 page, so there is no navigation stack, and that's why the back button exits the app. 

Page routing on the other hand (which is currentlly unstable, so I wouldn't recommend it) pushes new routes onto the navigation stack, so the back button works. But in this case you can't use a template with `router-view`. This is documented in detail here: https://nativescript-vue.org/en/docs/routing/vue-router/

And a couple suggestions about your code, you can use `v-show` to toggle visibility of elements, so for example instead of `:visibility="hasActionbar ? 'visible' : 'collapsed'"` you can use `v-show="hasActionbar"`.

Second, on your back button you are pushing back navigations onto the page stack, so you are always adding to the stack, and never removing. This can lead to memory issues.
Instead you should use `$router.back()` to navigate back to the previous page / component (when using component routing).

The issues with vuex are probably related to the fact that you are pushing to the navigation stack (but I can't be sure on this one without seeing more / trying it).

If you stick with component based routing, then you can use the [`activityBackPressedEvent`](https://docs.nativescript.org/api-reference/classes/_application_.androidapplication#activitybackpressedevent) and prevent it, and then just call `$router.back()`
