### ISSUE TITLE
Listview's Textfield focus problem

### ISSUE THREAD

**Issue by alemartins414** [nativescript-vue/nativescript-vue#166]
I've been working with nested v-for'ed layouts and right now I'm into this textfield focus problem.
Everytime I tap a textField, it's focus is misdirected to the first textField in the ListView as shown:

![issue](https://user-images.githubusercontent.com/14263182/38108202-777197d4-336a-11e8-9528-507bab579952.gif)

Any thoughts?

Repository with a demo below:
[https://github.com/alemartins414/textFieldDemo](url)

**Comment by rigor789** [comment]
Nesting a v-for inside a ListView template is a really bad idea! It will kill your performance, and break view recycling.

Instead use multiple templates, and flatten the list so it contains the headers and the list items, and select the correct template based on some property.

Here is a better way to do what you are after: https://play.nativescript.org/?template=play-vue&id=R2GMLR

This will still act weird as you scroll because view get reused, and then the focus can jump to a different field.

You may want to rething your layout/setup, listviews and textfields don't really mix well.

**Comment by alemartins414** [comment]
Thank you for your answer, @rigor789. 
Just achieved what I was looking for using regular StackLayouts instead ListView.
Although ListView's performance was quite better, unfortunately it doesn't fit to my goal.

Again, thank you :)
