### ISSUE TITLE
Access {N} functions for components used on template

### ISSUE THREAD

**Issue by rigoparis** [nativescript-vue/nativescript-vue#205]
Hey guys!

How can I access {N} functions in Nativescript-Vue components?

For example:
I have a ListView component
```
<ListView ref="list" for="msj in msjs" separatorColor="#fff">
 ...content...
</ListView>
```

How can I execute `scrollToIndex()` from the {N} ListView on that ref? Or what would be the proper approach to do this?

[https://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview#scrolltoindex](url)

Thanks in advance for any help provided and I'm sorry if this was asked before, I didn't seem to find the post.

**Comment by rigor789** [comment]
You can access the NativeScript element using 
```js
this.$refs.list.$el.nativeView.scrollToIndex()
```

Explanation:
 - `this.$refs.list` - access to the "DOM" element that you tagged with `ref="list"`
 - `$el` - because the above is actually a Vue component internally, we have to access the `<native-list-view>` element, `$el` does this.
 - `nativeView` - is the NativeScript view that is described in the linked docs.
