### ISSUE TITLE
[RFC] Use vue slots (instead of v-view) to handle named view arguments

### ISSUE THREAD

**Issue by championswimmer** [nativescript-vue/nativescript-vue#215]
Right now we use a `v-view` (or `~` shorthand) directive to pass views as arguments into components

```vue
<RadSideDrawer>
  <StackLayout ~drawerContent />
  <StackLayout ~mainContent />
</RadSideDrawer>
```

I would suggest we can use Vuejs slots, which already are meant for this purpose. 

```vue
<RadSideDrawer>
  <StackLayout slot="drawerContent" />
  <StackLayout slot="mainContent" />
</RadSideDrawer>
```

**Comment by championswimmer** [comment]
## Reasons

1. We do not end up reserving `v-view` or `~` shorthands, which Vue ecosystem may use in the future and we'll have compatibility problems. The slot syntax already exists in Vue ecosystem.

**Comment by byronferguson** [comment]
I don't quite get the current implementation of `v-view` now, but having something that used the native Vue approach to scopes makes a lot of sense to me (as a newbie).

**Comment by rigor789** [comment]
@byronferguson it exist to allow setting a view instance to a parents property - it's a mechanism that some nativescript components/plugins use but are not supported in Vue. To make the standard slot syntax work, we need to somehow distinguish between actual Vue slots and nativescript specific "slots". I'm not saying its impossible but needs testing and research, thus not a high priority at the moment, since `v-view` works just fine.
