### ISSUE TITLE
Cannot bind backgroundColor to a layout

### ISSUE THREAD

**Issue by tjvantoll** [nativescript-vue/nativescript-vue#229]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=L8tcfY&v=3](https://play.nativescript.org/?template=play-vue&id=L8tcfY&v=3)
### Platform and OS info
iOS 11, NativeScript 4.0.1

### Steps to reproduce
Run https://play.nativescript.org/?template=play-vue&id=L8tcfY&v=3.

### What is expected?
The page will render with a red box.

### What is actually happening?
The app crashes with an NSInvalidArgument exception.

---
This one is messing with me. If you do `backgroundColor="red"` the example works, but if you bind to a string with `"red"` it fails. I have no idea what’s going on, but any help would be appreciated. It’s possible that this affects more than just the `backgroundColor` property, but that’s what I hit.

**Comment by rigor789** [comment]
This is a limitation due to the way ListViews work in NativeScript, the views defined in the template have to be created up-front before the list goes through the items and tries to render them. That is a bit problematic because we don't have the data required within the template, and to solve this ns-vue uses a deeply nested Proxy object - which returns a Proxy up to the maximum depth of 10:

https://github.com/nativescript-vue/nativescript-vue/blob/93ea97168e53f9f1add3542192f90caf28d85034/platform/nativescript/runtime/components/v-template.js#L103-L108

https://github.com/nativescript-vue/nativescript-vue/blob/93ea97168e53f9f1add3542192f90caf28d85034/platform/nativescript/util/index.js#L99-L116


To avoid this, you unfortunately need to add a type check (or anything that prevents setting the `backgroundColor` property in this case to a `Proxy` object), example:
https://play.nativescript.org/?template=play-vue&id=L8tcfY&v=5

**Comment by rigor789** [comment]
I am interested to try if we can return nothing from the `createView()` function, and let the view patching part of the ListView take care of creating the views. I'll look into it.

**Comment by tjvantoll** [comment]
Thanks for the fast reply and workaround as always @rigor789—really appreciate it.

Just to note the Angular plugin doesn’t have this same problem, so I’m wondering what was done there to handle the same situation. If you need any help on my end let me know.
