### ISSUE TITLE
ActionBar gradient rendering bug

### ISSUE THREAD

**Issue by nmsdvid** [nativescript-vue/nativescript-vue#279]
I want to create a header gradient using nativescript-gradient but as you can see from the screenshot its not rendering correctly. The left side it has a small gap and its not 100% height.

<img width="377" alt="screen shot 2018-07-05 at 10 04 18" src="https://user-images.githubusercontent.com/1606990/42310101-d4e754a4-803a-11e8-87b4-d26742f18c44.png">

Code:
```
<ActionBar>
  <StackLayout>
    <Gradient direction="to right" colors="#ff6500, #fa0200">
       <Label text="Header" horizontalAlignment="center"
         style="color: white; width:100%; height: 100%; text-align:center" />
     </Gradient>
  </StackLayout>
</ActionBar>
```

**Comment by msaelices** [comment]
This issue is actually an Android theme issue. The Android default theme always put a padding in the ActionBar. See this NS issue, which was closed because is not related to NS: https://github.com/NativeScript/NativeScript/issues/4843

In the issue comments you will see some workaround, as putting a negative margin left. But I would recommend placing the gradient outside the action bar, as follows:

```
<Frame>
    <Page ref="page" actionBarHidden="true">
     <StackLayout>
       <Gradient direction="to right" colors="#ff6500, #fa0200">
          <Label text="Header" horizontalAlignment="center"
                      style="color: white; width:100%; height: 100%; text-align:center" />
       </Gradient>
      </StackLayout>
    ... 
    </Page>
</Frame>
```
