### ISSUE TITLE
ListView items doesn't get refreshed with component data other than the iterable item

### ISSUE THREAD

**Issue by FacundoMainere** [nativescript-vue/nativescript-vue#316]
### Version
1.3.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=lZNIFe](https://play.nativescript.org/?template=play-vue&id=lZNIFe)
### Platform and OS info
Android 7.1.1

### Steps to reproduce
Instantiate ListView inside any component and use component data that gets changed in some way

### What is expected?
The data to refresh on the ListView item when its changed on the component

### What is actually happening?
The item only refreshes for data inside the passed iterable item

**Comment by rigor789** [comment]
This is expected behavior, because the ListView's item template is rendered and updated by the list view when scrolling (view recycling), if you need to make sure the list view is updated when you change your property, call `refresh` on it. In `1.3.1` you can do `this.$refs.listView.nativeView.refresh()` and assign the ref to the ListView: `<ListView ref="listView" for...`

**Comment by FacundoMainere** [comment]
i understand.
Thank you!
