### ISSUE TITLE
ListView does not update on changes (on Android)

### ISSUE THREAD

**Issue by sStuehler** [nativescript-vue/nativescript-vue#333]
### Version
2.0.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=y9si9q](https://play.nativescript.org/?template=play-vue&id=y9si9q)
### Platform and OS info
Any Android

### Steps to reproduce
Clicking on edit/save

### What is expected?
Hide some Elements and show some other.

### What is actually happening?
Nothing. The List does not realize the change. 

---
Adding `this.scans = this.scans.slice()` in the onTapEdit() and onTabSave() methods is a workaround to fix the problem -
On iOS it works without any workaround.

**Comment by rigor789** [comment]
Using `v-if` in a ListView's ˛`v-template` defeats the purpose of using a ListView in the first place. The better approach would be to use multiple templates to keep view recycling optimal (and happy). A `v-template` is a scoped slot internally, so changes have to come from the parent to re-render them (in this case the ListView needs to be `refresh()`ed)

**Comment by sStuehler** [comment]
Using refreh() on the ListView works. Thanks.

But I couldn't define two v-templates having one with `<v-template if="isInEditMode">`. It seams to be that only variables of the list could be used (e.g. item.qty or index) in the if of the` v-template`, but not any js variable.

**Comment by rigor789** [comment]
Yeah the `if` props have a limited context to the item
https://github.com/nativescript-vue/nativescript-vue/blob/8c7f869025c4ba6d07d5d598c1b35117112ec16b/platform/nativescript/runtime/components/list-view.js#L87-L99

So if you don't want to add a property to each item, you will have to use the way you currently use it, but use `v-show` instead of `v-if`. v-show will create views for both states, but hide the ones that are not needed, this will help view recycling as the view hierarchy doesn't change, just the visibility property.

**Comment by sStuehler** [comment]
Thank you. Maybe the documentation could be enhanced and be a little more detailed.
