### ISSUE TITLE
how using nativescript-ui-calendar ?

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-vue/nativescript-vue#341]
I had read all doc on official website of telerik about nativescript-vue-calendar but nothing works, somoene can help me how using it ?
I use nativescript-vue@2.0.0 with .vue files

**Comment by rigor789** [comment]
Please open a new issue, with a minimal reproduction (a repository, that has the minimal amount of code that shows the issue), as otherwise there is nothing we can help with.

**Comment by Fabiyo-90** [comment]
All I need is an example how using nativescipt-ui-calendar ! 
ça va faire presque 3 mois ! 
tree month and no one help me

**Comment by rigor789** [comment]
There are docs, if that doesn't work for you, you need to create a reproduction that we can investigate... You can't expect help if you are not willing to provide what we ask for. 

> All I need is an example how using nativescipt-ui-calendar !

And all **we** need is a reproduction and a properly filled out issue.

You always open issues without following the issue helper / template. Why would anyone put in effort and help you (in their free time - for free), if you are not willing to put any effort into making it easier to help you?

I'm happy to help everyone, but I will not do the work instead of anyone. If you want the work to be done for you, hire someone - it's that simple.
