### ISSUE TITLE
new vue.js 2.6.0 v-slot syntax not supported

### ISSUE THREAD

**Issue by lhovee** [nativescript-vue/nativescript-vue#478]
### Version
2.2.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=5Dw8Pj](https://play.nativescript.org/?template=play-vue&id=5Dw8Pj)
### Platform and OS info
NA

### Steps to reproduce
try to use a named slot using the vue.js version 2.6.0 syntax "v-slot"

### What is expected?
using a named slot with the updated syntax like "v-slot:mySlotName" should render the designated content in the named slot and not render any default content in that named slot

### What is actually happening?
default content is rendered as well along with the designated content.

**Comment by lhovee** [comment]
follow up question on this: nativescript-vue has "vue": "^2.5.17" but the updated syntax for slots isn't supported. How can I tell what features are supported other than trial and error to see if they work? The nativescript-vue docs don't speak to this as far as I can tell.

**Comment by tralves** [comment]
Hi!
`v-slot` syntax [came with vue 2.6](https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax), so that's why it doesn't work.

Actually, I have been using a branch that adds support for Vue 2.6 and it still doesn't work and I can't figure out why. See issue here: https://github.com/nativescript-vue/nativescript-vue/pull/445#issuecomment-481219145.

**Comment by rigor789** [comment]
Supported in version [2.3.0-rc.0](https://github.com/nativescript-vue/nativescript-vue/releases/tag/v2.3.0-rc.0)
