### ISSUE TITLE
When can we expect production ready version

### ISSUE THREAD

**Issue by samayo** [nativescript-vue/nativescript-vue#48]
I have been expecting a nativescript for vuejs in a very long time, so thank you for making this. But it would be nice to know when there will be a release candidate

**Comment by flowck** [comment]
I agree with @samayo, I've been waiting for this in a very long time, in fact I came here today to ask if there's a roadmap or todo list so I and the rest of the community can help. I want to help. 

CC: @rigor789

**Comment by rigor789** [comment]
Hey! I am currently working on documentation, because that is one of the things that is required before we can call this production ready. It will take some time to have good documentation, but once we have the initial docs up and running, contributions will be very welcome! Ideally I would like to have automated tests for every important bit of code, but that is not something we have to have before we call it ready, but something that would be nice in the long run.

Another important thing is, we need feedback from people who are using it for semi-production apps, and by that I mean people who are building a production app that doesn't have to be published ASAP, but instead has time to find all the little bugs, issues with this integration, so we can work on fixing them.

I don't want to call something ready, and then have a bunch of issues piled up, because things are broken.

So in order to have feedback I would like as many people as possible to start using this either for side projects, or just to experiment with more than simple demos. Real world apps are never as simple as our demos are.

**Comment by flowck** [comment]
Thanks @rigor789, I'll start to right apps with it then.

**Comment by rigor789** [comment]
If you find any annoyances, bugs etc please let us know! You can also come chat with us on the NativeScript community slack (https://developer.telerik.com/wp-login.php?action=slack-invitation)

**Comment by xlcrr** [comment]
I'd like to help fill out the docs and make some sample apps.
It would be great to get some 1. example docs for the components and 2. instructions as to how we can dig into each component. For example I want a picker-view with 2 columns. I can get date-picker to work but how can I set properties for pickerview?
https://developer.apple.com/documentation/uikit/uipickerview

**Comment by rigor789** [comment]
@xlcrr I believe I have answered your questions on slack, if I didn't cover something let me know and I can do it :)

**Comment by chrishaff** [comment]
Could you please post that slack conversation here for the rest of us?

**Comment by rigor789** [comment]
Sure, I'll just paste the whole thing here

---

xlcr [13:51] 
How can I get started with <list-picker> ? I am looking for something like
```<list-picker
   v-if selectedIndex="0"
         items="["1", "2", "3"]"
   v-if selectedIndex="1"
         items="[2,3,4"]
    ></list-picker>
```
(edited)


rigor789 [13:53] 
v-if is for conditionally showing and hiding elements


[13:53] 
what you are looking for is a computed property

[13:53] 
let me show you an example


[13:57] 
https://play.nativescript.org/?template=play-vue&id=468Kybp1gg0_ryhstu9E0

 
[13:57] 
although in this case this doesn't make too much sense, as soon as you start scrolling the picker, it will change the items


xlcr [13:58] 
that's fantastic thanks!! I get computed props have been using vue for about a year. Got that working, thanks so much


[13:59] 
Once I get the hang of this I will help with the docs


rigor789
[13:59] 
https://play.nativescript.org/?template=play-vue&id=cHEL06YSXw0t9Nc62fa30


[13:59] 
this might illustrate it a bit better!


[13:59] 
as soon as you are not on the first element it changes to foo bar baz

[13:59] 
all the concepts are the same as in vue


[14:00] 
the main difference is the elements you can use and their properties


xlcr [14:00] 
very excited about this thank you so much!!


rigor789
[14:00] 
:vuespock:


xlcr [14:03] 
how can I change it to x2 picker wheels on the same picker?


rigor789
[14:12] 
You would use 2 pickers next to each other


[14:13] 
you want them to control separate values right?

xlcr [14:13] 
I want the picker to have 2-3 wheels in the same picker

[14:13] 
like date-picker has 3

[14:14] 
in uipickerview for swift its "numberOfComponents"

[14:17] 
In Swift its
```    // MARK: - PickerView Delegate Methods
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 2
    }
    
    // Return the number of rows in each component
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        if component == 0 {
            return self.inputArray.count
        }
```


rigor789
[14:17] 
Not sure about that one (that's more nativescript specific than vue specifc) but what I got working is this: https://play.nativescript.org/?template=play-vue&id=bOTdoKTB3w0aJEY6BZFZ0


xlcr [14:18] 
x2 pickers was my second guess! Thanks!


rigor789
[14:19] 
Seems to render properly on both iOS and android


[14:19] 
but there might be a better way to do it


[14:19] 
not sure

**Comment by jlooper** [comment]
1.0.0 is now in NPM!
