### ISSUE TITLE
Crashing when trying to change tabTextColor for iOS

### ISSUE THREAD

**Issue by kropcik** [nativescript-vue/nativescript-vue#482]
### Version
2.2.2

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=JM3nZz](https://play.nativescript.org/?template=play-vue&id=JM3nZz)
### Platform and OS info
MacOS Mojave, iOS 12.2

### Steps to reproduce
Load a view with following code:
```
<template>
    <Page actionBarHidden="true">
        <TabView tabBackgroundColor="white" tabTextColor="red">
            <TabViewItem title="Tab1">
                <Label text="Content for Tab 1" />
            </TabViewItem>
            <TabViewItem title="Tab2">
                <Label text="Content for Tab 2" />
            </TabViewItem>
            <TabViewItem title="Tab3">
                <Label text="Content for Tab 3" />
            </TabViewItem>
            <TabViewItem title="Tab4">
                <Label text="Content for Tab 4"/>
            </TabViewItem>
        </TabView>
    </Page>
</template>
```

### What is expected?
Loaded view with selected tab colors

### What is actually happening?
Crashing.
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'tabSelectedItemTextColor.ios')

**Comment by kropcik** [comment]
Solved.

As long as you add `tabTextColor` attribute to `<TabView>`, you also have to set `selectedTabTextColor` attribute. If both attributes is set, build runs fine.

**Comment by rigor789** [comment]
This has come up on Slack recently, the issue is in NativeScript core, as it has a wrong conditional. When setting `tabTextColor` you also need to set `selectedTabTextColor` or otherwise it will crash.

The cause is likely this line:

https://github.com/NativeScript/NativeScript/blob/4e56c89f7d63f69a8c8bd77a11314941851c1107/tns-core-modules/ui/tab-view/tab-view.ios.ts#L579

```js
 const selectedTextColor = tabItemTextColor instanceof Color ? tabSelectedItemTextColor.ios : null;
```
It checks if `tabItemTextColor` is instance of Color, but then accesses `tabSelectedItemTextColor` instead.

Would you mind opening an issue in the [NativeScript repository](https://github.com/NativeScript/NativeScript)?

**Comment by kropcik** [comment]
@rigor789 Sure.
