### ISSUE TITLE
frame$$1.back is not a function

### ISSUE THREAD

**Issue by fixer112** [nativescript-vue/nativescript-vue#491]
### Version
2.2.2

### Reproduction link
[https://github.com/fixer112/honeypays_app](https://github.com/fixer112/honeypays_app)
### Platform and OS info
Andriod 8.0/ Nativescript 5.3.4/MacOs 10.14.4

### Steps to reproduce
Click on calculator, news or contact, then try and click on the back icon on the appbar

### What is expected?
Expects to navigates back

### What is actually happening?
Any time i call $navigateBack i get frame$$1.back is not a function error

**Comment by rigor789** [comment]
When running the app I see a warning:
```
JS: [Vue warn]: Method "back" has already been defined as a data property.
JS:
JS: found in
JS:
JS: ---> <Frame>
JS:        <Root>
```

Which is caused by a global mixin that defines `back` as a data property on every vue instance. This collides with the frame's API which also has a method named `back`.

Essentially with that mixin, you are replacing the frame's `back` method with a boolean value.

After I commented out line 174 in main.js
https://github.com/fixer112/honeypays_app/blob/5b2f2f48dd390bbab89b7505e1798cbba0514459/app/main.js#L174

`$navigateBack` works fine.

**Comment by fixer112** [comment]
thanks a lot @rigor789 , such a silly mistake i did
