### ISSUE TITLE
In ListView, setting GridLayout's visibility to collapse doesn't work in Android

### ISSUE THREAD

**Issue by MustafaCa** [nativescript-vue/nativescript-vue#493]
### Version
2.2.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=LDb6sV&v=3](https://play.nativescript.org/?template=play-vue&id=LDb6sV&v=3)
### Platform and OS info
The issue is specific to Android - iOS works fine.

### Steps to reproduce
Start the app in the project link, tap on the blue text to collapse the list. On iOS it works as expected. In Android, tapping the blue text causes following lines to be hidden instead of collapsing.

### What is expected?
ListView items in GridLayout should collapse - i.e. the list should shrink in heigh.

### What is actually happening?
The list items disappear but the list doesn't shrink.

---
It works as expected in iOS.

**Comment by MustafaCa** [comment]
![image](https://user-images.githubusercontent.com/6033291/57825086-39aa5a80-7752-11e9-81ab-a8ac8606088d.png)

iPhone screen with correct collapse behavior
![image](https://user-images.githubusercontent.com/6033291/57825060-1a133200-7752-11e9-8680-1a59f7d4124c.png)

Android with visibility "collapse" behaving like "hidden"
![image](https://user-images.githubusercontent.com/6033291/57825105-547ccf00-7752-11e9-9330-c86ad5df30f9.png)

**Comment by rigor789** [comment]
Collapsing entire rows is a bad idea - as the listview has to calculate heights for each cell, it doesn't re-calculate when you collapse.

I see you're also nesting a `ListView` under a `ScrollView` - that's unnecessary, and will lead to weird issues down the line. This is not related to the question but thought I mention it!

What I suggest for you to do is actually remove elements from the list that you don't need to show. A computed property can do the job perfectly. I've updated your playground with a computed property:

https://play.nativescript.org/?template=play-vue&id=LDb6sV&v=4

There are ways to clean up the code - most notably the way you handle groups is hard to maintain - since you need to check with `if` statements whether it's `A` or `B`... 

An easier way I would prefer would be to have the items/templates like this:

```js
countries: [
  {
    name: "Tap to Collapse/Expand group A",
    isGroupHeader: true, 
    group: 'a',
    isCollapsed: false
  },
  {
    group: "a",
    name: "Australia",
    imageSrc: "https://play.nativescript.org/dist/assets/img/flags/au.png"
  }, ...
]
```
```html
<v-template if="country.isGroupHeader">
  <!-- Template for the group header -->
</v-template>

<v-template>
  <!-- Template for the items that are not headers -->
</v-template>
```

This way you can have a computed property for any number of groups:
```js
computed: {
  // written without a code editor / testing it so might not be 100% correct
  // but should get the point across!
  countriesWithoutCollapsed() {
    const collapsedGroupNames = this.countries.filter(
        country => !country.isCollapsed
    ).map(country => country.group)

    return this.countries.filter(country => !collapsedGroupNames.includes(country.group))
  }
}
```

**Comment by MustafaCa** [comment]
Thanks Igor. I really appreciate your prompt and informative reply. 

Actually, this was a sample I wrote to show the issue. While, the collapse logic is similar, my real app is a bit different than a simple grouping. Nevertheless, your suggestion helps to solve my issue. I will also see if I can use how you implemented grouping. Very smart! Thanks again.
