### ISSUE TITLE
How to use $navigateTo in natviescript-vue vuex store actions?

### ISSUE THREAD

**Issue by aranmohyeddin** [nativescript-vue/nativescript-vue#547]
`this.$navigateTo` works perfectly fine within the methods of my components, but inside a mutation neither of `Vue.$navigateTo` and `this.$navigateTo` work. My navigation depends on the result I get from an api call, if there is no way to perform a navigation from within store actions, how can I get some return value from an store action so I can perform my navigation within my component?

**Comment by fvdung** [comment]
You can use `Promise` in actions Vuex and `then - catch` it in dispatch function inside .vue file
Ex
```
actions: {
     anyAction() {
            return new Promise((resolve, reject) => {
                    // handle, commit, disatch ....
                    if (any condition) {
                            resolve()
                     }
                     reject()
            })
     }
}
```
.vue
```
this.$store.dispatch('anyAction').then(() => {
    // Resolve here
    this.$navigateTo(...)
}).catch(() => {
    // Reject
})
```

**Comment by aranmohyeddin** [comment]
@fvdung But what if I want to use mapActions? Is there any way to mak `$navigateTo` directly accessible within store? Is there any certain reason that navigation should not be done within store dispatch function?

**Comment by KonstantinObuhov** [comment]
@aranmohyeddin I think that it can't be accomplish as you want. I do like @fvdung wrote.

**Comment by rigor789** [comment]
You can try calling it via `Vue.prototype.$navigateTo(...)` and import vue from `nativescript-vue`. This is not the intended way, so I can't guarantee it will work...

Also there isn't anything different when using `mapActions` you still call the action from your component, and you can `await` or `.then()` the returned promise. This is a better approach than trying to navigate from Vuex, since the navigation is a side effect.

**Comment by aranmohyeddin** [comment]
Thanks everyone.
