### ISSUE TITLE
nativescript-vue 我喜欢nativescript-vue 

### ISSUE THREAD

**Issue by djroad** [nativescript-vue/nativescript-vue#585]
nativescript-vue 我喜欢nativescript-vue 

1).hope, nativescript-vue, Can support Android 4.4
2).hope, nativescript-vue, Can support         Call the Mobile phone address book
3).hope, nativescript-vue UI,  It can be the same as vux UI ( Url: "https://doc.vux.li/zh-
CN/components/cell.html" )
4).希望, nativescript-vue UI   It can be the same as element UI( Url: "https://element.eleme.io/#/en-US" )

Describe alternatives you've considered
 DCloud - HBuilder ( Url: "https://uniapp.dcloud.io/component/view" )

Additional context
Byte beat 公司

**Comment by tralves** [comment]
Hi! I don't understand Chinese, but I think I know what you are asking.

1) yes, you can build apps for Android 4.4 with NativeScript.
2, 3, 4) No, because those UI libraries are for "normal" html/css. NativeScript does not use HTML components. The markup and css is similar but not the same so none of that will work.

I advise you to test NS-Vue in the [playground](https://play.nativescript.org) to see how it works.
Re-open if you have further questions.
