### ISSUE TITLE
nested navigation with sidedrawer broken

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/nativescript-vue#763]
### Version
2.7.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=O2JYqr&v=3](https://play.nativescript.org/?template=play-vue&id=O2JYqr&v=3)
### Platform and OS info
iOS

### Steps to reproduce
[Share a Single RadSideDrawer throughout the Entire Life Cycle of the Application](https://docs.nativescript.org/angular/ui/ng-components/ng-sidedrawer/show-over-navi-bar) is the use case
It works correctly until `nativescript-vue` < `2.7.0` on iOS. (change in the playground app.js the `nativescript-vue` version to reproduce or use https://play.nativescript.org/?template=play-vue&id=O2JYqr&v=4).
![IMG_8485](https://user-images.githubusercontent.com/13959976/101358963-e354bd80-389b-11eb-8094-c9120f6af134.PNG)

### What is expected?
Working nested routing described here: https://docs.nativescript.org/angular/ui/ng-components/ng-sidedrawer/show-over-navi-bar

### What is actually happening?
`nativescript-vue` < `2.7.0` -> error
`nativescript-vue` >= `2.8.0` (NS7) -> z-index or order wrong (first page of history always in foreground)

---
now I had to upgrade to NS7 and  `nativescript-vue` >= `2.8.0`. Here seems ok (no error), but the next page seems being loaded, but behind the previous page inside the nested `<Frame />`

**Comment by rigor789** [comment]
@wendt88 make sure you are giving your frames unique id's - otherwise frames will have a `default` id - and if multiple frames are shown, the last one rendered will become the `default` frame. 

Adding the id - and the default page under the Content frame appears to be working as expected:
https://play.nativescript.org/?template=play-vue&id=Yh0k8j&v=3

**Comment by wendt88** [comment]
Thank you very much, you saved me.
adding an id resolved it. but I thought, name attribute is enough? before `2.7.0` it worked fine with name and `Frame.getFrameById(name)` worked too.

**Comment by rigor789** [comment]
@wendt88 don't think `name` made it prior to 2.7. Prior version had id conflict resolution by adding an incrementing integer if a conflicting id was found (eg. `default`, `default1`, `default2` etc) - however that introduced a bunch of different issues:
* unable to navigate a frame - since the id has "magically" changed
* id's changing occasionally when suspending/resuming - causing navigation to stop working

So it has been removed - as it was really just masking a problem in the users code - using explicit unique id's is the right solution to make things consistent and working!
